name: React CI/CD

on:
  push:
    branches: [main]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run build
      - name: Deploy
        run: 
          git config --global user.name 'test'
          git config --global user.email 'test@test.com'
          npm run deploy
      
